spring:
  mail:
    host: smtp.163.com
    username: ankkiceshi@163.com
    password: cESHI123
    port: 25
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
    default-encoding: utf-8